### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by ChapperNi** [jasmaa/niconico-yt#5]
Settings keep resetting to default when I restart my browser.

**Comment by jasmaa** [comment]
This is most likely due to the background script [storing the settings in-memory](https://github.com/jasmaa/niconico-yt/blob/main/src/entrypoints/background.ts#L14-L18). When the browser restarts, the bg script restarts and the settings are lost.

I can probably look into making it use [web storage](https://developer.chrome.com/docs/extensions/reference/api/storage) instead.

**Comment by jasmaa** [comment]
Fix is merged into main. It should be included in the next release.
